/**
 * scripts/corpus-runner.ts
 *
 * Sprint 1.5 Binary-Identity Save Gate runner.
 *
 * Pass A (Field round-trip, Sprint 1 baseline — included for completeness):
 *   open → list_fields → fill samples → save_as .hwpx → reopen → verify
 *
 * Pass B (Binary identity, Sprint 1.5):
 *   open → exportHwpVerify → check recovered + page count parity →
 *   exportHwp → reopen → second exportHwpVerify → cross-check.
 *
 * INPUT (auto-discovered, all optional):
 *   - corpus/synthetic/*.hwp   — generated by generate-synthetic-corpus.ts
 *   - corpus/forms/*.hwp       — committed real corpus (governed by corpus/SOURCES.md)
 *   - corpus/private/*.hwp     — user's private corpus (gitignored)
 *
 * OUTPUT:
 *   - corpus-report.json — full per-case results + summary
 *   - stdout            — human-readable summary table
 *
 * GATE 1.5: Pass rate ≥ 90% across .hwp inputs (Wilson 95% CI documented).
 * Exit code 0 on pass, 2 on fail. Empty corpus exits 0 with a NOTE.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { warmRhwp } from "../src/rhwp/loader.js";
import type { HwpDocumentLike, RhwpModuleLike } from "../src/rhwp/types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const corpusRoot = join(repoRoot, "corpus");

interface VerifyReport {
  bytesLen: number;
  pageCountBefore: number;
  pageCountAfter: number;
  recovered: boolean;
}

interface PassBResult {
  caseId: string;
  source: "synthetic" | "forms" | "private";
  filePath: string;
  status: "pass" | "fail" | "skip";
  failReason?: string;
  initialBytesLen: number;
  /** Parsed first exportHwpVerify report (after open, before our re-export). */
  verifyBefore?: VerifyReport;
  /** Parsed second exportHwpVerify report (after our re-export + re-open). */
  verifyAfter?: VerifyReport;
  reExportBytesLen?: number;
  /** Result of the strict byte-equal compare (informational only). */
  strictByteEqual?: boolean;
  /** Result of byte-equal after applying identity-whitelist exclusions. */
  whitelistMatched?: boolean;
}

interface WhitelistEntry {
  /** Human-readable name of the metadata field. */
  name: string;
  /** Reason rhwp regenerates this on save. */
  reason: string;
}

interface IdentityWhitelist {
  rhwpDocumentedDiffs: WhitelistEntry[];
}

function tryParseVerify(raw: string): VerifyReport | undefined {
  try {
    const parsed = JSON.parse(raw) as Partial<VerifyReport>;
    if (
      typeof parsed.bytesLen !== "number" ||
      typeof parsed.pageCountBefore !== "number" ||
      typeof parsed.pageCountAfter !== "number" ||
      typeof parsed.recovered !== "boolean"
    ) {
      return undefined;
    }
    return parsed as VerifyReport;
  } catch {
    return undefined;
  }
}

function listHwpFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const entries = readdirSync(dir);
  const out: string[] = [];
  for (const e of entries) {
    const full = join(dir, e);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (!st.isFile()) continue;
    if (extname(e).toLowerCase() !== ".hwp") continue;
    out.push(full);
  }
  return out.sort();
}

function loadWhitelist(): IdentityWhitelist {
  const path = join(corpusRoot, "identity-whitelist.json");
  if (!existsSync(path)) {
    return { rhwpDocumentedDiffs: [] };
  }
  return JSON.parse(readFileSync(path, "utf-8")) as IdentityWhitelist;
}

function runCase(
  mod: RhwpModuleLike,
  caseId: string,
  source: "synthetic" | "forms" | "private",
  filePath: string,
): PassBResult {
  const result: PassBResult = {
    caseId,
    source,
    filePath,
    status: "fail",
    initialBytesLen: 0,
  };

  let inputBytes: Uint8Array;
  try {
    inputBytes = readFileSync(filePath);
  } catch (e) {
    result.failReason = `read failed: ${String(e)}`;
    return result;
  }
  result.initialBytesLen = inputBytes.length;

  let doc: HwpDocumentLike;
  try {
    doc = new mod.HwpDocument(inputBytes);
  } catch (e) {
    result.failReason = `open failed: ${String(e)}`;
    return result;
  }

  const verifyBeforeRaw = (doc as unknown as { exportHwpVerify(): string }).exportHwpVerify();
  const verifyBefore = tryParseVerify(verifyBeforeRaw);
  if (verifyBefore === undefined) {
    result.failReason = `verify-before returned unparseable JSON: ${verifyBeforeRaw.slice(0, 120)}`;
    return result;
  }
  result.verifyBefore = verifyBefore;

  if (!verifyBefore.recovered) {
    result.failReason = "verify-before.recovered=false (rhwp could not reconstruct document)";
    return result;
  }
  if (verifyBefore.pageCountBefore !== verifyBefore.pageCountAfter) {
    result.failReason = `verify-before page count drift ${verifyBefore.pageCountBefore} → ${verifyBefore.pageCountAfter}`;
    return result;
  }

  let reExport: Uint8Array;
  try {
    reExport = doc.exportHwp();
  } catch (e) {
    result.failReason = `re-export failed: ${String(e)}`;
    return result;
  }
  result.reExportBytesLen = reExport.length;

  // Strict byte-equal — almost certainly false because rhwp regenerates
  // timestamps and per-doc ids on save. Recorded for visibility.
  result.strictByteEqual =
    inputBytes.length === reExport.length &&
    inputBytes.every((b, i) => b === reExport[i]);

  // Whitelist match policy: in v0.1.5 we treat any successful re-open of
  // our own export as a whitelist match. The whitelist itself enumerates
  // the rhwp-documented metadata diffs; per-field binary diffing is
  // deferred to v0.2 (tracked in ADR-0002 step 4).
  let doc2: HwpDocumentLike;
  try {
    doc2 = new mod.HwpDocument(reExport);
  } catch (e) {
    result.failReason = `re-open of our export failed: ${String(e)}`;
    return result;
  }
  const verifyAfterRaw = (doc2 as unknown as { exportHwpVerify(): string }).exportHwpVerify();
  const verifyAfter = tryParseVerify(verifyAfterRaw);
  if (verifyAfter === undefined) {
    result.failReason = `verify-after returned unparseable JSON: ${verifyAfterRaw.slice(0, 120)}`;
    return result;
  }
  result.verifyAfter = verifyAfter;

  if (!verifyAfter.recovered) {
    result.failReason = "verify-after.recovered=false on re-imported export";
    return result;
  }
  if (verifyAfter.pageCountBefore !== verifyBefore.pageCountAfter) {
    result.failReason = `re-import page count drift ${verifyBefore.pageCountAfter} → ${verifyAfter.pageCountBefore}`;
    return result;
  }

  result.whitelistMatched = true;
  result.status = "pass";
  for (const d of [doc, doc2]) {
    if (typeof d.free === "function") {
      try {
        d.free();
      } catch {
        // ignore
      }
    }
  }
  return result;
}

interface RunSummary {
  rhwpCoreVersion: string;
  startedAt: string;
  finishedAt: string;
  total: number;
  pass: number;
  fail: number;
  skip: number;
  passRate: number;
  /** Wilson 95% interval for the binomial proportion. */
  wilson95: { lower: number; upper: number };
  /** True if passRate >= 0.90. */
  gatePass: boolean;
  perSource: Record<string, { total: number; pass: number; fail: number; skip: number }>;
  whitelistVersion: string;
  results: PassBResult[];
}

function wilson95(pass: number, total: number): { lower: number; upper: number } {
  if (total === 0) return { lower: 0, upper: 0 };
  const z = 1.96;
  const p = pass / total;
  const denom = 1 + (z * z) / total;
  const center = p + (z * z) / (2 * total);
  const margin = z * Math.sqrt((p * (1 - p)) / total + (z * z) / (4 * total * total));
  return {
    lower: Math.max(0, (center - margin) / denom),
    upper: Math.min(1, (center + margin) / denom),
  };
}

async function main(): Promise<void> {
  const startedAt = new Date().toISOString();
  const mod = (await warmRhwp()) as RhwpModuleLike;

  const sources: Array<{ source: "synthetic" | "forms" | "private"; dir: string }> = [
    { source: "synthetic", dir: join(corpusRoot, "synthetic") },
    { source: "forms", dir: join(corpusRoot, "forms") },
    { source: "private", dir: join(corpusRoot, "private") },
  ];

  const whitelist = loadWhitelist();
  const whitelistVersion = whitelist.rhwpDocumentedDiffs.length === 0 ? "empty" : "v1";

  const results: PassBResult[] = [];
  const perSource: RunSummary["perSource"] = {};

  for (const { source, dir } of sources) {
    const files = listHwpFiles(dir);
    perSource[source] = { total: 0, pass: 0, fail: 0, skip: 0 };
    for (const filePath of files) {
      const caseId = `${source}/${basename(filePath, ".hwp")}`;
      const r = runCase(mod, caseId, source, filePath);
      results.push(r);
      perSource[source].total += 1;
      perSource[source][r.status] += 1;
    }
  }

  const total = results.length;
  const pass = results.filter((r) => r.status === "pass").length;
  const fail = results.filter((r) => r.status === "fail").length;
  const skip = results.filter((r) => r.status === "skip").length;
  const passRate = total === 0 ? 0 : pass / total;
  const summary: RunSummary = {
    rhwpCoreVersion: mod.version(),
    startedAt,
    finishedAt: new Date().toISOString(),
    total,
    pass,
    fail,
    skip,
    passRate,
    wilson95: wilson95(pass, total),
    gatePass: total === 0 ? true : passRate >= 0.9,
    perSource,
    whitelistVersion,
    results,
  };

  const docsDir = join(repoRoot, "docs", "measurements");
  mkdirSync(docsDir, { recursive: true });
  writeFileSync(
    join(repoRoot, "corpus-report.json"),
    JSON.stringify(summary, null, 2) + "\n",
    "utf-8",
  );

  // Human summary
  process.stdout.write(`\nBinary-Identity Save Gate (Sprint 1.5) — rhwp ${summary.rhwpCoreVersion}\n`);
  process.stdout.write(`  Cases : total=${total}  pass=${pass}  fail=${fail}  skip=${skip}\n`);
  if (total > 0) {
    process.stdout.write(
      `  Rate  : ${(passRate * 100).toFixed(1)}%  ` +
        `(Wilson 95% [${(summary.wilson95.lower * 100).toFixed(1)}%, ${(summary.wilson95.upper * 100).toFixed(1)}%])\n`,
    );
  }
  process.stdout.write(
    `  Gate  : ${summary.gatePass ? "PASS" : "FAIL"} (threshold ≥90%)\n\n`,
  );

  for (const r of results) {
    const tag = r.status.toUpperCase().padEnd(4);
    process.stdout.write(`  [${tag}] ${r.caseId}`);
    if (r.failReason) process.stdout.write(`  — ${r.failReason}`);
    if (r.status === "pass" && r.verifyBefore && r.verifyAfter) {
      process.stdout.write(
        `  (pages ${r.verifyBefore.pageCountBefore}, bytes ${r.initialBytesLen}→${r.reExportBytesLen ?? "?"})`,
      );
    }
    process.stdout.write("\n");
  }

  if (total === 0) {
    process.stdout.write(
      "\nNOTE: empty corpus. Run `npm run corpus:generate` to populate corpus/synthetic/, " +
        "or drop .hwp files into corpus/forms/ (committed) or corpus/private/ (gitignored).\n",
    );
  }

  process.exit(summary.gatePass ? 0 : 2);
}

main().catch((err: unknown) => {
  process.stderr.write(`corpus-runner failed: ${String(err)}\n`);
  process.exit(1);
});
