/**
 * scripts/corpus-runner.ts
 *
 * Corpus gate runner.
 *
 * Pass A — Field round-trip (Sprint 3, ADR-0006):
 *   open → getFieldList → fill synthetic values → exportHwp(x) → reopen →
 *   re-fetch field list → verify field names preserved + value round-trip.
 *   Cases with zero form fields skip Pass A (counted as "skip", not "fail").
 *
 * Pass B — Binary identity (Sprint 1.5, ADR-0002):
 *   open → exportHwpVerify → check recovered + page count parity →
 *   exportHwp → reopen → second exportHwpVerify → cross-check.
 *   Reserved for HWP 5.0 sources. .hwpx sources skip Pass B (the gate is
 *   defined against the HWP 5.0 binary write contract).
 *
 * Combined case status:
 *   - pass : both passes are pass-or-skip, AND at least one is pass.
 *   - fail : either pass is fail.
 *   - skip : both passes are skip (no signal at all from this case).
 *
 * Rate denominator excludes skips (rate = pass / (pass + fail)) so cases
 * with no testable signal don't drag the rate down. Documented in ADR-0006.
 *
 * INPUT (auto-discovered, all optional):
 *   - corpus/synthetic/*.hwp{,x} — generated by generate-synthetic-corpus.ts
 *   - corpus/forms/*.hwp{,x}     — committed real corpus (governed by corpus/SOURCES.md)
 *   - corpus/private/*.hwp{,x}   — user's private corpus (gitignored)
 *
 * OUTPUT:
 *   - corpus-report.json — full per-case results + summary
 *   - stdout            — human-readable summary table
 *
 * Decision Gate — threshold escalates with corpus size:
 *   - total < 30 : Sprint 1.5 baseline gate, threshold ≥ 90%
 *   - total ≥ 30 : Sprint 3 Decision Gate 3.0, threshold ≥ 95%
 *
 * Exit code 0 on pass, 2 on fail. Empty corpus exits 0 with a NOTE.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { basename, dirname, extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { warmRhwp } from "../src/rhwp/loader.js";
import type { HwpDocumentLike, RhwpFieldEntry, RhwpModuleLike } from "../src/rhwp/types.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, "..");
const corpusRoot = join(repoRoot, "corpus");

const DECISION_GATE_3_THRESHOLD = 0.95;
const SPRINT_1_5_THRESHOLD = 0.9;
const DECISION_GATE_3_MIN_N = 30;

type SourceBucket = "synthetic" | "forms" | "private";
type SourceFormat = "hwp" | "hwpx";
type PassStatus = "pass" | "fail" | "skip";

interface VerifyReport {
  bytesLen: number;
  pageCountBefore: number;
  pageCountAfter: number;
  recovered: boolean;
}

interface PassAResult {
  status: PassStatus;
  fieldCount: number;
  filledCount: number;
  reopenedFieldCount: number;
  valueRoundtripOk: boolean;
  failReason?: string;
}

interface PassBResult {
  status: PassStatus;
  initialBytesLen: number;
  reExportBytesLen?: number;
  verifyBefore?: VerifyReport;
  verifyAfter?: VerifyReport;
  /** Result of the strict byte-equal compare (informational only). */
  strictByteEqual?: boolean;
  /** Result of byte-equal after applying identity-whitelist exclusions. */
  whitelistMatched?: boolean;
  failReason?: string;
}

interface CaseResult {
  caseId: string;
  source: SourceBucket;
  sourceFormat: SourceFormat;
  filePath: string;
  /** Combined status — see header docstring for combination rules. */
  status: PassStatus;
  /** Why the case rolled up to this status (always set when status='fail'). */
  combinedReason?: string;
  passA: PassAResult;
  passB: PassBResult;
}

interface WhitelistEntry {
  /** Human-readable name of the metadata field. */
  name: string;
  /** Reason rhwp regenerates this on save. */
  reason: string;
}

interface IdentityWhitelist {
  rhwpDocumentedDiffs: WhitelistEntry[];
}

export function tryParseVerify(raw: string): VerifyReport | undefined {
  try {
    const parsed = JSON.parse(raw) as Partial<VerifyReport>;
    if (
      typeof parsed.bytesLen !== "number" ||
      typeof parsed.pageCountBefore !== "number" ||
      typeof parsed.pageCountAfter !== "number" ||
      typeof parsed.recovered !== "boolean"
    ) {
      return undefined;
    }
    return parsed as VerifyReport;
  } catch {
    return undefined;
  }
}

function listCorpusFiles(dir: string): string[] {
  if (!existsSync(dir)) return [];
  const entries = readdirSync(dir);
  const out: string[] = [];
  for (const e of entries) {
    const full = join(dir, e);
    let st;
    try {
      st = statSync(full);
    } catch {
      continue;
    }
    if (!st.isFile()) continue;
    const ext = extname(e).toLowerCase();
    if (ext !== ".hwp" && ext !== ".hwpx") continue;
    out.push(full);
  }
  return out.sort();
}

function loadWhitelist(): IdentityWhitelist {
  const path = join(corpusRoot, "identity-whitelist.json");
  if (!existsSync(path)) {
    return { rhwpDocumentedDiffs: [] };
  }
  return JSON.parse(readFileSync(path, "utf-8")) as IdentityWhitelist;
}

function detectFormat(inputBytes: Uint8Array, fileExt: string): SourceFormat {
  // Trust extension first (no rhwp call needed). HWPX is a ZIP (starts PK\x03\x04);
  // HWP 5.0 is a CFB (starts D0 CF 11 E0). We could sniff, but the extension
  // matches the canonical convention 100% of the time on our corpus.
  if (fileExt === ".hwpx") return "hwpx";
  if (fileExt === ".hwp") return "hwp";
  // Fallback for hypothetical extension-less files: peek the magic.
  if (inputBytes.length >= 4 && inputBytes[0] === 0x50 && inputBytes[1] === 0x4b) return "hwpx";
  return "hwp";
}

/**
 * Pass A — fill every known form field with a deterministic synthetic value,
 * round-trip through export/reopen, and verify field-name preservation +
 * value round-trip.
 *
 * Synthetic value pattern: `value-N` where N is the index in the field list
 * order returned by getFieldList(). Deterministic so re-runs are stable.
 *
 * Skips with status='skip' (no fail) when the document has zero form fields —
 * Pass A is a measurement of round-trip integrity, not a requirement that
 * every document must carry fields.
 */
export function runPassA(
  mod: RhwpModuleLike,
  inputBytes: Uint8Array,
  sourceFormat: SourceFormat,
): PassAResult {
  const result: PassAResult = {
    status: "fail",
    fieldCount: 0,
    filledCount: 0,
    reopenedFieldCount: 0,
    valueRoundtripOk: false,
  };

  let doc: HwpDocumentLike;
  try {
    doc = new mod.HwpDocument(inputBytes);
  } catch (e) {
    result.failReason = `Pass A: open failed: ${String(e)}`;
    return result;
  }

  let fieldsBefore: RhwpFieldEntry[];
  try {
    const raw = doc.getFieldList();
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed)) {
      result.failReason = `Pass A: getFieldList returned non-array: ${typeof parsed}`;
      return result;
    }
    fieldsBefore = (parsed as RhwpFieldEntry[]).filter(
      (f): f is RhwpFieldEntry => typeof f?.name === "string" && f.name.length > 0,
    );
  } catch (e) {
    result.failReason = `Pass A: getFieldList parse failed: ${String(e)}`;
    return result;
  }

  result.fieldCount = fieldsBefore.length;

  if (fieldsBefore.length === 0) {
    result.status = "skip";
    return result;
  }

  // Fill each field with a deterministic synthetic value.
  const targetValues = new Map<string, string>();
  for (let i = 0; i < fieldsBefore.length; i++) {
    const name = fieldsBefore[i].name;
    const value = `value-${i + 1}`;
    targetValues.set(name, value);
    try {
      const setRaw = doc.setFieldValueByName(name, value);
      const setParsed = JSON.parse(setRaw) as { ok?: boolean; message?: string };
      if (setParsed.ok !== true) {
        result.failReason = `Pass A: setFieldValueByName(${name}) returned ${JSON.stringify(setParsed)}`;
        return result;
      }
      result.filledCount += 1;
    } catch (e) {
      result.failReason = `Pass A: setFieldValueByName(${name}) threw: ${String(e)}`;
      return result;
    }
  }

  // Re-export preserving the source format so the round-trip stays in-format.
  let reExport: Uint8Array;
  try {
    reExport = sourceFormat === "hwpx" ? doc.exportHwpx() : doc.exportHwp();
  } catch (e) {
    result.failReason = `Pass A: re-export failed: ${String(e)}`;
    return result;
  }

  let doc2: HwpDocumentLike;
  try {
    doc2 = new mod.HwpDocument(reExport);
  } catch (e) {
    result.failReason = `Pass A: re-open failed: ${String(e)}`;
    return result;
  }

  let fieldsAfter: RhwpFieldEntry[];
  try {
    const raw2 = doc2.getFieldList();
    const parsed2 = JSON.parse(raw2) as unknown;
    if (!Array.isArray(parsed2)) {
      result.failReason = `Pass A: re-open getFieldList non-array: ${typeof parsed2}`;
      return result;
    }
    fieldsAfter = (parsed2 as RhwpFieldEntry[]).filter(
      (f): f is RhwpFieldEntry => typeof f?.name === "string" && f.name.length > 0,
    );
  } catch (e) {
    result.failReason = `Pass A: re-open getFieldList parse failed: ${String(e)}`;
    return result;
  }
  result.reopenedFieldCount = fieldsAfter.length;

  if (fieldsAfter.length !== fieldsBefore.length) {
    result.failReason =
      `Pass A: field count drift ${fieldsBefore.length} → ${fieldsAfter.length}`;
    freeDocs([doc, doc2]);
    return result;
  }

  const expectedNames = new Set(fieldsBefore.map((f) => f.name));
  const actualNames = new Set(fieldsAfter.map((f) => f.name));
  for (const n of expectedNames) {
    if (!actualNames.has(n)) {
      result.failReason = `Pass A: field name '${n}' missing after re-open`;
      freeDocs([doc, doc2]);
      return result;
    }
  }

  // Value round-trip: re-read every field via getFieldValueByName and
  // confirm it matches the synthetic value we set above.
  let allValuesMatched = true;
  for (const [name, expected] of targetValues) {
    try {
      const getRaw = doc2.getFieldValueByName(name);
      const getParsed = JSON.parse(getRaw) as { ok?: boolean; value?: string };
      if (getParsed.ok !== true) {
        result.failReason = `Pass A: getFieldValueByName(${name}) ok!=true`;
        allValuesMatched = false;
        break;
      }
      if (getParsed.value !== expected) {
        result.failReason =
          `Pass A: value drift on field '${name}' — sent '${expected}', got '${getParsed.value ?? "<undefined>"}'`;
        allValuesMatched = false;
        break;
      }
    } catch (e) {
      result.failReason = `Pass A: getFieldValueByName(${name}) threw: ${String(e)}`;
      allValuesMatched = false;
      break;
    }
  }
  result.valueRoundtripOk = allValuesMatched;
  freeDocs([doc, doc2]);
  if (!allValuesMatched) return result;

  result.status = "pass";
  return result;
}

/**
 * Pass B — open, exportHwpVerify, re-export, re-open, second exportHwpVerify.
 * The historical Sprint 1.5 binary-identity gate, scoped to HWP 5.0 sources.
 * .hwpx sources skip with reason — the gate's contract is HWP-5.0-specific
 * (ADR-0002).
 */
export function runPassB(
  mod: RhwpModuleLike,
  inputBytes: Uint8Array,
  sourceFormat: SourceFormat,
): PassBResult {
  const result: PassBResult = {
    status: "fail",
    initialBytesLen: inputBytes.length,
  };

  if (sourceFormat === "hwpx") {
    result.status = "skip";
    result.failReason = "Pass B reserved for HWP 5.0 sources (ADR-0002, ADR-0006).";
    return result;
  }

  let doc: HwpDocumentLike;
  try {
    doc = new mod.HwpDocument(inputBytes);
  } catch (e) {
    result.failReason = `Pass B: open failed: ${String(e)}`;
    return result;
  }

  const verifyBeforeRaw = (doc as unknown as { exportHwpVerify(): string }).exportHwpVerify();
  const verifyBefore = tryParseVerify(verifyBeforeRaw);
  if (verifyBefore === undefined) {
    result.failReason = `Pass B: verify-before unparseable: ${verifyBeforeRaw.slice(0, 120)}`;
    return result;
  }
  result.verifyBefore = verifyBefore;

  if (!verifyBefore.recovered) {
    result.failReason = "Pass B: verify-before.recovered=false";
    return result;
  }
  if (verifyBefore.pageCountBefore !== verifyBefore.pageCountAfter) {
    result.failReason =
      `Pass B: verify-before page count drift ${verifyBefore.pageCountBefore} → ${verifyBefore.pageCountAfter}`;
    return result;
  }

  let reExport: Uint8Array;
  try {
    reExport = doc.exportHwp();
  } catch (e) {
    result.failReason = `Pass B: re-export failed: ${String(e)}`;
    return result;
  }
  result.reExportBytesLen = reExport.length;

  // Strict byte-equal — almost certainly false because rhwp regenerates
  // timestamps and per-doc ids on save. Recorded for visibility.
  result.strictByteEqual =
    inputBytes.length === reExport.length &&
    inputBytes.every((b, i) => b === reExport[i]);

  // Whitelist match policy: in v0.1.5 we treat any successful re-open of
  // our own export as a whitelist match. The whitelist itself enumerates
  // the rhwp-documented metadata diffs; per-field binary diffing is
  // deferred to v0.2 (tracked in ADR-0002 step 4).
  let doc2: HwpDocumentLike;
  try {
    doc2 = new mod.HwpDocument(reExport);
  } catch (e) {
    result.failReason = `Pass B: re-open of our export failed: ${String(e)}`;
    return result;
  }
  const verifyAfterRaw = (doc2 as unknown as { exportHwpVerify(): string }).exportHwpVerify();
  const verifyAfter = tryParseVerify(verifyAfterRaw);
  if (verifyAfter === undefined) {
    result.failReason = `Pass B: verify-after unparseable: ${verifyAfterRaw.slice(0, 120)}`;
    return result;
  }
  result.verifyAfter = verifyAfter;

  if (!verifyAfter.recovered) {
    result.failReason = "Pass B: verify-after.recovered=false on re-imported export";
    return result;
  }
  if (verifyAfter.pageCountBefore !== verifyBefore.pageCountAfter) {
    result.failReason =
      `Pass B: re-import page count drift ${verifyBefore.pageCountAfter} → ${verifyAfter.pageCountBefore}`;
    return result;
  }

  result.whitelistMatched = true;
  result.status = "pass";
  freeDocs([doc, doc2]);
  return result;
}

function freeDocs(docs: HwpDocumentLike[]): void {
  for (const d of docs) {
    if (typeof d.free === "function") {
      try {
        d.free();
      } catch {
        // ignore
      }
    }
  }
}

/**
 * Combine Pass A + Pass B into a single case verdict.
 * - fail if either pass failed
 * - pass if at least one passed and neither failed
 * - skip if both skipped (no signal)
 */
export function combine(passA: PassAResult, passB: PassBResult): {
  status: PassStatus;
  combinedReason?: string;
} {
  if (passA.status === "fail") return { status: "fail", combinedReason: passA.failReason };
  if (passB.status === "fail") return { status: "fail", combinedReason: passB.failReason };
  if (passA.status === "pass" || passB.status === "pass") return { status: "pass" };
  return {
    status: "skip",
    combinedReason: "both passes skipped — no testable signal from this case",
  };
}

function runCase(
  mod: RhwpModuleLike,
  caseId: string,
  source: SourceBucket,
  filePath: string,
): CaseResult {
  const inputBytes = readFileSync(filePath);
  const sourceFormat = detectFormat(inputBytes, extname(filePath).toLowerCase());
  const passA = runPassA(mod, inputBytes, sourceFormat);
  const passB = runPassB(mod, inputBytes, sourceFormat);
  const { status, combinedReason } = combine(passA, passB);
  return {
    caseId,
    source,
    sourceFormat,
    filePath,
    status,
    combinedReason,
    passA,
    passB,
  };
}

interface RunSummary {
  rhwpCoreVersion: string;
  startedAt: string;
  finishedAt: string;
  total: number;
  pass: number;
  fail: number;
  skip: number;
  /** rate = pass / (pass + fail) — skips excluded from denominator. */
  passRate: number;
  /** Wilson 95% interval for the binomial proportion on the rated set. */
  wilson95: { lower: number; upper: number };
  /** Threshold actually applied this run (depends on rated total). */
  threshold: number;
  thresholdSource: "decision-gate-3" | "sprint-1.5-baseline" | "empty";
  gatePass: boolean;
  perSource: Record<string, { total: number; pass: number; fail: number; skip: number }>;
  whitelistVersion: string;
  results: CaseResult[];
}

function wilson95(pass: number, denom: number): { lower: number; upper: number } {
  if (denom === 0) return { lower: 0, upper: 0 };
  const z = 1.96;
  const p = pass / denom;
  const factor = 1 + (z * z) / denom;
  const center = p + (z * z) / (2 * denom);
  const margin = z * Math.sqrt((p * (1 - p)) / denom + (z * z) / (4 * denom * denom));
  return {
    lower: Math.max(0, (center - margin) / factor),
    upper: Math.min(1, (center + margin) / factor),
  };
}

export function selectThreshold(rated: number): {
  threshold: number;
  source: RunSummary["thresholdSource"];
} {
  if (rated === 0) return { threshold: 0, source: "empty" };
  if (rated >= DECISION_GATE_3_MIN_N) {
    return { threshold: DECISION_GATE_3_THRESHOLD, source: "decision-gate-3" };
  }
  return { threshold: SPRINT_1_5_THRESHOLD, source: "sprint-1.5-baseline" };
}

async function main(): Promise<void> {
  const startedAt = new Date().toISOString();
  const mod = (await warmRhwp()) as RhwpModuleLike;

  const sources: Array<{ source: SourceBucket; dir: string }> = [
    { source: "synthetic", dir: join(corpusRoot, "synthetic") },
    { source: "forms", dir: join(corpusRoot, "forms") },
    { source: "private", dir: join(corpusRoot, "private") },
  ];

  const whitelist = loadWhitelist();
  const whitelistVersion = whitelist.rhwpDocumentedDiffs.length === 0 ? "empty" : "v1";

  const results: CaseResult[] = [];
  const perSource: RunSummary["perSource"] = {};

  for (const { source, dir } of sources) {
    const files = listCorpusFiles(dir);
    perSource[source] = { total: 0, pass: 0, fail: 0, skip: 0 };
    for (const filePath of files) {
      const caseId = `${source}/${basename(filePath, extname(filePath))}`;
      let r: CaseResult;
      try {
        r = runCase(mod, caseId, source, filePath);
      } catch (e) {
        r = {
          caseId,
          source,
          sourceFormat: "hwp",
          filePath,
          status: "fail",
          combinedReason: `runner threw before pass logic: ${String(e)}`,
          passA: {
            status: "fail",
            fieldCount: 0,
            filledCount: 0,
            reopenedFieldCount: 0,
            valueRoundtripOk: false,
            failReason: "runner threw before Pass A could execute",
          },
          passB: {
            status: "fail",
            initialBytesLen: 0,
            failReason: "runner threw before Pass B could execute",
          },
        };
      }
      results.push(r);
      perSource[source].total += 1;
      perSource[source][r.status] += 1;
    }
  }

  const total = results.length;
  const pass = results.filter((r) => r.status === "pass").length;
  const fail = results.filter((r) => r.status === "fail").length;
  const skip = results.filter((r) => r.status === "skip").length;
  const rated = pass + fail;
  const passRate = rated === 0 ? 0 : pass / rated;
  const { threshold, source: thresholdSource } = selectThreshold(rated);

  const summary: RunSummary = {
    rhwpCoreVersion: mod.version(),
    startedAt,
    finishedAt: new Date().toISOString(),
    total,
    pass,
    fail,
    skip,
    passRate,
    wilson95: wilson95(pass, rated),
    threshold,
    thresholdSource,
    gatePass: total === 0 ? true : passRate >= threshold,
    perSource,
    whitelistVersion,
    results,
  };

  const docsDir = join(repoRoot, "docs", "measurements");
  mkdirSync(docsDir, { recursive: true });
  writeFileSync(
    join(repoRoot, "corpus-report.json"),
    JSON.stringify(summary, null, 2) + "\n",
    "utf-8",
  );

  const gateLabel = (() => {
    switch (thresholdSource) {
      case "decision-gate-3":
        return "Sprint 3 Decision Gate 3.0 (Pass A + Pass B combined)";
      case "sprint-1.5-baseline":
        return "Binary-Identity Save Gate (Sprint 1.5 baseline — pre-N=30)";
      default:
        return "Corpus gate";
    }
  })();

  // Human summary
  process.stdout.write(`\n${gateLabel} — rhwp ${summary.rhwpCoreVersion}\n`);
  process.stdout.write(
    `  Cases : total=${total}  pass=${pass}  fail=${fail}  skip=${skip}\n`,
  );
  if (rated > 0) {
    process.stdout.write(
      `  Rate  : ${(passRate * 100).toFixed(1)}%  (rated=${rated}, skips excluded)  ` +
        `Wilson 95% [${(summary.wilson95.lower * 100).toFixed(1)}%, ${(summary.wilson95.upper * 100).toFixed(1)}%]\n`,
    );
  }
  process.stdout.write(
    `  Gate  : ${summary.gatePass ? "PASS" : "FAIL"} (threshold ≥${(threshold * 100).toFixed(0)}%)\n\n`,
  );

  for (const r of results) {
    const tag = r.status.toUpperCase().padEnd(4);
    process.stdout.write(
      `  [${tag}] ${r.caseId}.${r.sourceFormat} ` +
        `(A=${r.passA.status}, B=${r.passB.status})`,
    );
    if (r.combinedReason) process.stdout.write(`  — ${r.combinedReason}`);
    if (r.status === "pass" && r.passB.verifyBefore && r.passB.verifyAfter) {
      process.stdout.write(
        `  (pages ${r.passB.verifyBefore.pageCountBefore}, bytes ${r.passB.initialBytesLen}→${r.passB.reExportBytesLen ?? "?"})`,
      );
    }
    process.stdout.write("\n");
  }

  if (total === 0) {
    process.stdout.write(
      "\nNOTE: empty corpus. Run `npm run corpus:generate` to populate corpus/synthetic/, " +
        "or drop .hwp / .hwpx files into corpus/forms/ (committed) or corpus/private/ (gitignored).\n",
    );
  }

  process.exit(summary.gatePass ? 0 : 2);
}

// Run main() only when invoked directly (`npm run gate:binary-identity` /
// `tsx scripts/corpus-runner.ts`). Imports from tests skip the script-style
// side effect so the runtime path stays decoupled from unit tests of the
// individual pass functions.
const invokedDirectly =
  process.argv[1] !== undefined &&
  fileURLToPath(import.meta.url) === resolve(process.argv[1]);
if (invokedDirectly) {
  main().catch((err: unknown) => {
    process.stderr.write(`corpus-runner failed: ${String(err)}\n`);
    process.exit(1);
  });
}
