/**
 * schema-snapshot.ts
 *
 * Regenerate schemas/snapshot.json from the live zod schemas exported by each
 * tool module. Run this script whenever a tool schema changes, then commit
 * the new snapshot WITH a CHANGELOG.md entry that describes the change.
 *
 * Usage:
 *   npm run schema:snapshot     # rewrites schemas/snapshot.json in place
 *
 * The companion script scripts/schema-diff.ts compares the live schemas
 * against the committed snapshot on every PR and blocks merge if they
 * differ without a CHANGELOG entry. Both scripts pull their tool list from
 * scripts/_shared/schemas.ts so they cannot drift apart.
 *
 * Why this exists: public API stability is Principle 3 in the plan. Without
 * a snapshot guard, signatures can drift silently as developers iterate
 * inside src/tools/*.ts.
 */

import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

import { liveSchemas, TOOL_COUNT } from "./_shared/schemas.js";

const SNAPSHOT_PATH = resolve(process.cwd(), "schemas", "snapshot.json");
const PKG_JSON_PATH = resolve(process.cwd(), "package.json");

async function readPkgVersion(): Promise<string> {
  try {
    const raw = await readFile(PKG_JSON_PATH, "utf8");
    const pkg = JSON.parse(raw) as { version?: unknown };
    if (typeof pkg.version === "string" && pkg.version.length > 0) {
      return pkg.version;
    }
  } catch {
    // fall through
  }
  return "unknown";
}

async function main(): Promise<void> {
  const version = await readPkgVersion();
  const tools = liveSchemas();
  const snapshot = {
    $comment:
      "Auto-generated by scripts/schema-snapshot.ts — do not edit by hand. " +
      "Regenerate via `npm run schema:snapshot`. Changes must be accompanied " +
      "by a CHANGELOG.md entry referencing the affected tool.",
    version,
    generated_by: "scripts/schema-snapshot.ts",
    generated_at: new Date().toISOString(),
    tool_count_expected: TOOL_COUNT,
    tools,
  };
  await writeFile(SNAPSHOT_PATH, JSON.stringify(snapshot, null, 2) + "\n", "utf8");
  process.stderr.write(
    `schema-snapshot: wrote ${SNAPSHOT_PATH} (${Object.keys(tools).length} tools, v${version})\n`,
  );
}

main().catch((err: unknown) => {
  const message = err instanceof Error ? err.message : String(err);
  process.stderr.write(`schema-snapshot failed: ${message}\n`);
  process.exit(1);
});
